run:
  tests: true
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

linters:
  disable-all: true
  enable:
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

# TODO: fix the sdkerrors.Wrap deprecation warning and re-enable staticcheck
# TODO: fix the use of deprecated gov style

issues:
  exclude-rules:
    - text: "SA1019: sdkerrors.Register"
      linters:
        - staticcheck
    - text: "sdkerrors.ABCIInfo is deprecated"
      linters:
        - staticcheck
    - text: "sdkerrors.IsOf is deprecated"
      linters:
        - staticcheck
    - text: "Use WeightedProposalMsg instead"
      linters:
        - staticcheck
    - text: "Use MsgSimulatorFn instead"
      linters:
        - staticcheck
    - text: "Error return value of `flagSet.Set` is not checked"
      linters:
        - errcheck
    - text: "SA1019: sdkerrors.Wrapf is deprecated: functionality of this package has been moved to it's own module"
      linters:
        - staticcheck
    - text: "sdkerrors.Error is deprecated: the type has been moved to cosmossdk.io/errors module"
      linters:
        - staticcheck
    - text: "sdkerrors.Wrap is deprecated"
      linters:
        - staticcheck
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck
    - path: "migrations"
      text: "SA1019:"
      linters:
        - staticcheck

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
