name: Build wasmd

on:
  pull_request:
  push:
    branches:
      - main
      - gh-actions-demo # TODO: REMOVE THIS

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Build
        run: make build