name: Tests / Code Coverage
#  Tests / Code Coverage workflow runs unit tests and uploads a code coverage report
#  This workflow is run on pushes to main & every Pull Requests where a .go, .mod, .sum have been changed
on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
    - run: go install ./...
    