on: [push, pull_request]
name: every commit
jobs:

  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: make build
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test


# Here, I separated benchmarks for more granular performance info

  wasmgas:
    runs-on: ubuntu-latest
    name: wasm gas
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: benchmarks
        run: |
          cd ./x/wasm/keeper
          go test -bench .
          

  wasm-vs-native:
    runs-on: ubuntu-latest
    name: wasm compared to native modules
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: wasm vs native
        run: |
          cd ./benchmarks
          go test -bench .


  sim:
    runs-on: ubuntu-latest
    name: Multi Seed Sim
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run Multi Seed Simulation
        run: make test-sim-multi-seed-short


  race:
    runs-on: ubuntu-latest
    name: Race conditions test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: 
        run: make test-race


  proto-breaking:
    runs-on: ubuntu-latest
    name: check protobufs for breaking changes
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: make proto-check-breaking



  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2


  CosmoSec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run CosmoSec Security Scanner
        uses: informalsystems/gosec@master
        with:
          args: ./...


  
