name: Simulation tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  sim-tests:
    name: Run wamsd simulation tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        test:
          [
            test-sim-import-export,
            test-sim-multi-seed-short,
            test-sim-deterministic,
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Run {{ matrix.test }}
        run: make {{ matrix.test }}

